// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phkfxxgdsqewuxqklmnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBoa2Z4eGdkc3Fld3V4cWtsbW56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NjE0NjQsImV4cCI6MjA2NzQzNzQ2NH0.OBnboHMo6cnJHk6g4_NxKkxLfcLlh3aSsn_aog52UlA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});